<package format="2">
  <name>geonova</name>
  <version>0.1.0</version>
  <description>The My ROS Package with utils</description>

  <maintainer email="pjmsm0319@gmail.com">dbparkJ</maintainer>
  <license>BSD</license>

  <!-- ROS 기본 의존성 -->
  <buildtool_depend>catkin</buildtool_depend>

  <!-- ROS Python 종속성 -->
  <build_depend>rospy</build_depend>
  <build_depend>std_msgs</build_depend>
  <exec_depend>rospy</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <!-- msg 의존성 -->
  <build_depend>message_generation</build_depend>
  <exec_depend>message_generation</exec_depend>
  <exec_depend>message_runtime</exec_depend>

  <!-- Python 관련 의존성 -->
  <build_depend>python3</build_depend>
  <exec_depend>python3</exec_depend>
  <build_depend>setuptools</build_depend>
  <exec_depend>setuptools</exec_depend>

  <!-- setup.py를 통한 설치 지원 -->
  <export>
    <build_type>catkin</build_type>
  </export>
</package>
